"""Demo scenario controller — the presenter's remote control.

* ``advance_day``   steps simulated time forward by one day, revealing that
  day's observations (deterministic baseline + any active event impact).
* ``trigger``       declares the scripted Red Sea / Jeddah disruption.
* ``reset``         rebuilds the seed state.

Nothing here fabricates a forecast. Triggering the scenario only inserts
*events*; the forecast moves because ``services/events.py`` propagates those
events through the port graph, and the observed history catches up as the clock
advances.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..config import SEED_TODAY
from ..models import Chokepoint, DemoState, Event, Port, PortDaily
from ..seed import baseline_observation, reset_database
from ..world import PORTS_BY_ID, SCENARIO_EVENTS
from .events import RISK_LOOKAHEAD_DAYS, EventOverlay, clear_topology_cache, congestion_to_waiting
from .forecast import clear_forecast_snapshots

MAX_SIM_DAYS = 40  # the deterministic future buffer generated by seed.py


@dataclass
class DemoStateView:
    sim_date: date
    seed_date: date
    days_advanced: int
    scenario_active: bool
    scenario_day: int
    scenario_start: date | None
    data_version: int
    can_advance: bool


def get_state(db: Session) -> DemoState:
    state = db.get(DemoState, 1)
    if state is None:
        state = DemoState(id=1, sim_date=SEED_TODAY, scenario_active=False, scenario_day=0, data_version=1)
        db.add(state)
        db.flush()
    return state


def state_view(db: Session) -> DemoStateView:
    s = get_state(db)
    return DemoStateView(
        sim_date=s.sim_date,
        seed_date=SEED_TODAY,
        days_advanced=(s.sim_date - SEED_TODAY).days,
        scenario_active=s.scenario_active,
        scenario_day=s.scenario_day,
        scenario_start=s.scenario_start,
        data_version=s.data_version,
        can_advance=(s.sim_date - SEED_TODAY).days < MAX_SIM_DAYS,
    )


def _insert_due_scenario_events(db: Session, state: DemoState) -> list[Event]:
    """Insert scripted events whose declaration day has now arrived."""
    if not state.scenario_active or state.scenario_start is None:
        return []
    existing = {e.id for e in db.execute(select(Event).where(Event.scenario.is_(True))).scalars()}
    added: list[Event] = []
    for i, (offset, etype, sev, headline, detail, port_id, cp_id) in enumerate(SCENARIO_EVENTS):
        day = state.scenario_start + timedelta(days=offset)
        if day > state.sim_date:
            continue
        event_id = f"EVS-{i:03d}"
        if event_id in existing:
            continue
        if port_id:
            lat, lon = PORTS_BY_ID[port_id].lat, PORTS_BY_ID[port_id].lon
        elif cp_id:
            cp = db.get(Chokepoint, cp_id)
            lat, lon = (cp.lat, cp.lon) if cp else (0.0, 0.0)
        else:
            lat, lon = 0.0, 0.0
        event = Event(
            id=event_id,
            day=day,
            type=etype,
            severity=sev,
            headline=headline,
            detail=detail,
            port_id=port_id,
            chokepoint_id=cp_id,
            lat=lat,
            lon=lon,
            source="PortPulse live feed",
            scenario=True,
        )
        db.add(event)
        added.append(event)
    if added:
        db.flush()
    return added


def _refresh_chokepoint_risk(db: Session, as_of: date) -> None:
    """Store the risk facing a vessel entering the strait in the next few days,
    which is what a planner actually needs, rather than today's instant."""
    overlay = EventOverlay(db, as_of)
    lookahead = as_of + timedelta(days=RISK_LOOKAHEAD_DAYS)
    for cp in db.execute(select(Chokepoint)).scalars():
        cp.current_risk = overlay.chokepoint_risk(db, cp.id, lookahead)
    db.flush()


def _write_observations(db: Session, day: date) -> int:
    """Reveal one day of observations: deterministic baseline + event impact."""
    overlay = EventOverlay(db, day)
    existing = {
        pid for (pid,) in db.execute(select(PortDaily.port_id).where(PortDaily.day == day)).all()
    }
    written = 0
    for port in db.execute(select(Port)).scalars():
        if port.id in existing:
            continue
        base = baseline_observation(port.id, day)
        uplift = overlay.congestion_uplift(port.id, day).congestion
        congestion = min(max(base["congestion_index"] + uplift, 4.0), 99.0)
        waiting = base["waiting_days"]
        if abs(uplift) >= 0.05:
            waiting = max(
                0.05,
                waiting
                + congestion_to_waiting(base["congestion_index"] + uplift)
                - congestion_to_waiting(base["congestion_index"]),
            )
        db.add(
            PortDaily(
                port_id=port.id,
                day=day,
                congestion_index=round(congestion, 2),
                waiting_days=round(waiting, 3),
                weather_severity=base["weather_severity"],
                vessel_arrivals=base["vessel_arrivals"],
                scenario=abs(uplift) >= 0.05,
            )
        )
        written += 1
    db.flush()
    return written


def advance_day(db: Session) -> DemoStateView:
    state = get_state(db)
    if (state.sim_date - SEED_TODAY).days >= MAX_SIM_DAYS:
        return state_view(db)

    state.sim_date = state.sim_date + timedelta(days=1)
    if state.scenario_active and state.scenario_start is not None:
        state.scenario_day = (state.sim_date - state.scenario_start).days

    _insert_due_scenario_events(db, state)
    _write_observations(db, state.sim_date)
    _refresh_chokepoint_risk(db, state.sim_date)
    state.data_version += 1
    db.flush()
    return state_view(db)


def trigger(db: Session) -> DemoStateView:
    state = get_state(db)
    if state.scenario_active:
        return state_view(db)
    state.scenario_active = True
    state.scenario_start = state.sim_date
    state.scenario_day = 0
    _insert_due_scenario_events(db, state)
    _refresh_chokepoint_risk(db, state.sim_date)
    state.data_version += 1
    db.flush()
    return state_view(db)


def reset(db: Session) -> DemoStateView:
    reset_database(db)
    clear_topology_cache()
    clear_forecast_snapshots()
    return state_view(db)
